enum class Country(val code: String) {
    AFGHANISTAN("AF"),
    ALBANIA("AL"),
    ALGERIA("DZ"),
    ANDORRA("AD"),
    ANGOLA("AO"),
    ANGUILLA("AI"),
    ANTARCTICA("AQ"),
    ANTIGUA_BARBUDA("AG"),
    ARGENTINA("AR"),
    ARMENIA("AM"),
    ARUBA("AW"),
    AUSTRALIA("AU"),
    AUSTRIA("AT"),
    AZERBAIJAN("AZ"),
    BAHAMAS("BS"),
    BAHRAIN("BH"),
    BANGLADESH("BD"),
    BARBADOS("BB"),
    BELARUS("BY"),
    BELGIUM("BE"),
    BELIZE("BZ"),
    BENIN("BJ"),
    BERMUDA("BM"),
    BHUTAN("BT"),
    BOLIVIA("BO"),
    BOSNIA("&"),
    BOTSWANA("BW"),
    BOUVET_ISLAND("BV"),
    BRAZIL("BR"),
    BRUNEI("BN"),
    BULGARIA("BG"),
    BURKINA("FASO"),
    MYANMAR("MM"),
    BURUNDI("BI"),
    CAMBODIA("KH"),
    CAMEROON("CM"),
    CANADA("CA"),
}

@OptIn(ExperimentalStdlibApi::class)
fun findByCodeViaEntries(code: String): Country? = Country.entries.find { it.code == code }

fun findByCodeViaValues(code: String): Country? = Country.values().find { it.code == code }
